### ISSUE TITLE
Not working on Windows 11

### ISSUE THREAD

**Issue by demonoid75** [seadhy/Spotify-Account-Creator#1]
Downloaded the pack and run the install but after after pressing a button the software close. Any suggestions?

**Comment by seadhy** [comment]
Please send error text or screenshot and config.json.

**Comment by demonoid75** [comment]
I cannot send a screenshoot as I cannot run the software on my PC. When I try to run Install it closes....when I'm on "installing modules" and I have to press a key to continue after pressing it closes

**Comment by seadhy** [comment]
Delete 'cls' line and again run install.bat, then send screenshot to console.

**Comment by demonoid75** [comment]
I tried away but nothing when I run install it close.....have you a guide what I need and how to install?

**Comment by seadhy** [comment]
Open cmd and write
```bat
httpx==0.23.0
colorama==0.4.6
pystyle==2.9
```
 to script one by one

**Comment by demonoid75** [comment]
here you go!
<img width="446" alt="Screenshot 2022-11-24 224555" src="https://user-images.githubusercontent.com/118575859/203867097-93372a9c-589f-48f7-b773-b946b7509486.png">

**Comment by seadhy** [comment]
uh sorry dude, please try again with what i changed

**Comment by demonoid75** [comment]
Same...
<img width="522" alt="Screenshot 2022-11-25 174951" src="https://user-images.githubusercontent.com/118575859/204028543-c5db5994-d081-4725-9bf3-4e97f1faba94.png">

**Comment by demonoid75** [comment]
Same....
<img width="522" alt="Screenshot 2022-11-25 174951" src="https://user-images.githubusercontent.com/118575859/204029214-e3d1688b-3125-43a3-9e9f-525f43c92455.png">

**Comment by seadhy** [comment]
Add python to path

**Comment by seadhy** [comment]
this thing took quite a long time, i'm closing it. You can easily find it by researching on google.
