### ISSUE TITLE
Just now working

### ISSUE THREAD

**Issue by perunavich** [seadhy/Spotify-Account-Creator#14]
Start program with - 
[00:17:35] [Error Occurred] > Account not created.

**Comment by seadhy** [comment]
the tool is working for now, check again config file and proxies.

**Comment by utqqpasha** [comment]
Start program with -
[00:18:32] [Error Occurred] > Account not created.

Do I have to use a proxy to avoid this error, if so, should the proxies in "proxies.txt" be like this 1) 139,162.255.79:10000
2) 139.162.255.79:10001

**Comment by air46** [comment]
try to use proxies, I had a few issues where it ended up stopping the program because my ip was sending too many requests. u can get free proxies from a website, and what worked for me was setting the threads higher (in config)
