### ISSUE TITLE
What OS does it work?

### ISSUE THREAD

**Issue by ethereak** [seadhy/Spotify-Account-Creator#15]
Is this just on windows? or does it also support MacOs?

**Comment by kunci115** [comment]
if you are not a developer it only work for windows. but if you  are a developer, you need to remove 
this in console/ change into another logging lib for linux/macos need

` from ctypes import windll`

> Is this just on windows? or does it also support MacOs?

**Comment by seadhy** [comment]
yes but u need to make small simple changes
