### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Minhe173** [seadhy/Spotify-Account-Creator#17]
![image](https://user-images.githubusercontent.com/88653001/222966830-019a5862-013d-44c1-bd5b-768e231d0106.png)

**Comment by Minhe173** [comment]
@seadhy

**Comment by seadhy** [comment]
Download all modules one by one

**Comment by Minhe173** [comment]
already

**Comment by Minhe173** [comment]
still error

**Comment by Minhe173** [comment]
@seadhy

**Comment by seadhy** [comment]
https://www.youtube.com/watch?v=SrX5yo4KKGM
