### ISSUE TITLE
i am getting an error

### ISSUE THREAD

**Issue by Ergun09** [seadhy/Spotify-Account-Creator#20]
![C__Windows_system32_cmd exe 19 03 2023 14_47_38](https://user-images.githubusercontent.com/76555218/226173732-aec6a2e0-6a01-4db4-b343-37c498ea4b29.png)

NameError: name 'ctypes' is not defined.Did you mean: 'type' and account not created.

**Comment by seadhy** [comment]
Download the new version. (@ImmaSB I wish I had checked your pull request :D)

**Comment by Ergun09** [comment]
thanks fixed
