### ISSUE TITLE
fix this

### ISSUE THREAD

**Issue by 1mazinsalah1** [seadhy/Spotify-Account-Creator#30]
i changed config.json and it's not working
Traceback (most recent call last):
  File "C:\Users\windows\Desktop\Spotify-Account-Creator-main\creator.py", line 557, in <module>
    gen = Gen()
          ^^^^^
  File "C:\Users\windows\Desktop\Spotify-Account-Creator-main\creator.py", line 58, in __init__
    self.config_file = json.load(open('data/config.json', 'r', encoding='utf-8'))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\windows\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\imSkyDie\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\windows\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\windows\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
C:\Users\windows\Desktop\Spotify-Account-Creator-main>PAUSEn 25 (char 614)

**Comment by 1mazinsalah1** [comment]
{
    "settings": {
        "Threads": 3,
        "Create_Username": "y",
	"Create_Avatar": "y",
        "Change_Avatar": "y",
        "Use_Proxy": "n",
	"Remove_Bad_Proxies": "n",
        "Debug_Mode": "if you are not a developer, do not touch this value!! (if you're going to change you can just do 'y')"
    },
    
    "verification_settings": {
        "Verify_Mail": "n",
        "Services": {
            "Use_MailTM": "n",
            "Use_Emailnator": "n"
        }
    },
	
    "target_settings": {
        "Use_Target": "y",
        "Target_To": 3
    },

    "follow_ids": {
        "Account_IDs": ["account id1", "account id2", "account id 3 (u can put as many as you want)"],
        "Playlist_IDs": ["playlist id1", "playlist id2 (u can put as many as you want)"],
        "Artist_IDs": ["artist id1", "artist id (u can put as many as you want)"]
    },

    "follow_types": {
        "Profile": "n",
        "Playlist": "n",
        "Artist": "n"
    },

    "save_methods": {
        "SQLite": "y",
        "Text_File": "y"
    }
}

**Comment by seadhy** [comment]
What type of shipping is this? Throw it all in between the ```. Or take a screenshot

**Comment by 1mazinsalah1** [comment]
![image](https://user-images.githubusercontent.com/130707423/232563500-97cad90e-6e4f-4755-8f85-cd52707738ff.png)

**Comment by seadhy** [comment]
Just download the tool again and run run.bat. You will not get such an error.

**Comment by 1mazinsalah1** [comment]
still error
