### ISSUE TITLE
doesnt work at all

### ISSUE THREAD

**Issue by nismo1337** [seadhy/Spotify-Account-Creator#33]
![image](https://user-images.githubusercontent.com/61671297/235381960-7ffa2e02-d30b-40f2-89ac-392ebeb2f517.png)

**Comment by seadhy** [comment]
use paid proxies or use without proxies

**Comment by nismo1337** [comment]
im not using proxies 
![image](https://user-images.githubusercontent.com/61671297/235383792-b76edbc4-7509-4f4c-a4bb-e34727ea7af8.png)

**Comment by enriluis** [comment]
> use paid proxies or use without proxies

i dont use paid proxy, i cant buy proxy... so i set verify mail and get this error too.... and disable and runn fine...

**Comment by seadhy** [comment]
> im not using proxies ![image](https://user-images.githubusercontent.com/61671297/235383792-b76edbc4-7509-4f4c-a4bb-e34727ea7af8.png)

open debug mode and send ss again

> > use paid proxies or use without proxies
> 
> i dont use paid proxy, i cant buy proxy... so i set verify mail and get this error too.... and disable and runn fine...

try with without proxy

**Comment by enriluis** [comment]
> 

yes... it run fine without proxy and the email verification off, but when i set to yes the email verification i get this error too
![imagen](https://user-images.githubusercontent.com/47234519/235543558-cd5a0faf-baf8-492b-abe0-beca9721dffc.png)

**Comment by seadhy** [comment]
try again with updated code
