### ISSUE TITLE
account not created

### ISSUE THREAD

**Issue by hulibaba00** [seadhy/Spotify-Account-Creator#34]
i am using nord vpn but i am getting this error only the program is running for 2 minutes
![Ekran görüntüsü 2023-05-04 175818](https://user-images.githubusercontent.com/123498785/236247161-f7362f3f-34a9-4a5d-92b0-808ee4ca6f6f.png)

**Comment by hulibaba00** [comment]
{
    "settings": {
        "Threads": 3,
        "Create_Username": "y",
	"Create_Avatar": "y",
        "Change_Avatar": "y",
        "Use_Proxy": "n",
	"Remove_Bad_Proxies": "n",
        "Debug_Mode": "y"
    },
    
    "verification_settings": {
        "Verify_Mail": "n",
        "Services": {
            "Use_MailTM": "n",
            "Use_Emailnator": "n"
        }
    },
	
    "target_settings": {
        "Use_Target": "y",
        "Target_To": 10
    },

    "follow_ids": {
        "Account_IDs": ["xxx"],
        "Playlist_IDs": ["xxx"],
        "Artist_IDs": ["xxx"]
    },

    "follow_types": {
        "Profile": "y",
        "Playlist": "y",
        "Artist": "y"
    },

    "save_methods": {
        "SQLite": "y",
        "Text_File": "y"
    }
}

**Comment by seadhy** [comment]
try again with updated code
