### ISSUE TITLE
rate limit 

### ISSUE THREAD

**Issue by enriluis** [seadhy/Spotify-Account-Creator#4]
i'm testing this script ,but i getting the following error

can i set some value to respect spotify rate limit, the number of account to create? 
![imagen](https://user-images.githubusercontent.com/47234519/205672283-0a4002d0-27df-49d0-8b11-191e99d13117.png)

**Comment by seadhy** [comment]
You can create 200 accounts on Spotify without proxies. There is no such feature at the moment, but it may be added in the future. When it gets 50 stars I will add a lot of new options. You can give a star to the project to reach it faster!
