### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 27 column 9 (char 693)

### ISSUE THREAD

**Issue by m6xteen** [seadhy/Spotify-Account-Creator#41]
![Screenshot (396)](https://github.com/seadhy/Spotify-Account-Creator/assets/136198706/ceb91e88-47c8-4bd6-bbaf-e481ee5e0416)
NEWBIE. PLEASE HELP!

**Comment by seadhy** [comment]
fix ur config file

**Comment by macray795** [comment]
Thanks a million
