### ISSUE TITLE
Cannot access local variable 'proxies' where it is not associated with a value. Retrying... 

### ISSUE THREAD

**Issue by zhilanazmi** [seadhy/Spotify-Account-Creator#44]
![image](https://github.com/seadhy/Spotify-Account-Creator/assets/37895612/73cfe9bc-5b6b-45fb-987a-3e2a357a3d5b)

**Comment by danielmorris710** [comment]
same

**Comment by seadhy** [comment]
i fixed the issue. try again with updated code
