### ISSUE TITLE
Error creating accounts

### ISSUE THREAD

**Issue by chrisbalance1** [seadhy/Spotify-Account-Creator#45]
Using IP or proxies bot could not make accounts. You can use "user-Agent" spoofing technique. Currently in code it have static "user-Agent" strings if we can spoof that one it will increase requests per IP. Change the method of getting api token. Spotify has changed the api calls methods a-lot and this project is using old methods.

**Comment by enriluis** [comment]
exist some fork of this project using method as u recommended?

**Comment by seadhy** [comment]
try again with updated code
