### ISSUE TITLE
266 starts we need 250 thing

### ISSUE THREAD

**Issue by 1mazinsalah1** [seadhy/Spotify-Account-Creator#47]
![image](https://github.com/seadhy/Spotify-Account-Creator/assets/130707423/4f879a95-1ae6-4f14-95a7-6877207798b9)

**Comment by enriluis** [comment]
267 starred!

**Comment by enriluis** [comment]
right now the script  are not working, seems spotify api has been update and made some change....  the script should be updated  too :(

**Comment by seadhy** [comment]
updated, try again

**Comment by 1mazinsalah1** [comment]
we need the change passowrd feature
