### ISSUE TITLE
Account Creation not working anymore.

### ISSUE THREAD

**Issue by maximilianosinski** [seadhy/Spotify-Account-Creator#49]
Spotify changed it's signup process, whenever a account is created a `session_id` gets returned, this is then used to complete the creation (this happens on the signup web page), but the request to the `complete-creation` endpoint fails, because a reCAPTCHA token is required.

Maybe you'll find any fix for this, good luck.

**Comment by seadhy** [comment]
Yes. I added this to the code. Try again
