### ISSUE TITLE
can run on linux?

### ISSUE THREAD

**Issue by enriluis** [seadhy/Spotify-Account-Creator#53]
I recently migrate all virtual machines  on my  Lab to linux OS because i can send commands ex play, pause, open a play list to spotify native client via dbus-send on ubuntu VM  this is a great advantage for me and my be for other too.... will be useful if this script can run on linux....

**Comment by seadhy** [comment]
probably yes, test it

**Comment by enriluis** [comment]
![image](https://github.com/seadhy/Spotify-Account-Creator/assets/47234519/b3e03d45-705e-40ef-bbfa-90912b5ba642)
Yes it work on Ubuntu 20.04
