### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by Harry1Botter** [seadhy/Spotify-Account-Creator#9]
This tool is not working anymore. Bot creates accounts without saving them in txt.file plus bot does not following playlists/artist/user.

**Comment by seadhy** [comment]
Its funny to say that it doesnt run the program and definitively 'not working anymore'. Watch the [setup video](https://streamable.com/v4ooti) carefully and do the same. The program is working.

**Comment by Harry1Botter** [comment]
Hello, me and some other friends tried following the video, very easy to set up, but four of us had the same issue.

**Comment by seadhy** [comment]
You all filled the config.json file wrong, send me the config.json file.

**Comment by Harry1Botter** [comment]
A bit weird of all of us filled wrong the files using different devices in different locations. Anyway, will send you a screenshot or video asap. Thanks!!

**Comment by Harry1Botter** [comment]
![20221217_195830](https://user-images.githubusercontent.com/120516842/208257427-3f4cac92-9691-4371-aa15-c20b676b21d6.jpg)
Heres an example of my config.json file.

**Comment by seadhy** [comment]
![image](https://user-images.githubusercontent.com/82868382/208265376-bfa0f598-f2b6-4f70-9419-30934c683ab0.png)
Change with account/playlist/artist id.

**Comment by Harry1Botter** [comment]
Of course i use id's as the picture is just an example

**Comment by seadhy** [comment]
Can you try with the config.json file I sent?

**Comment by Harry1Botter** [comment]
![20221217_215026](https://user-images.githubusercontent.com/120516842/208265581-0ba25fda-1fc3-421c-a4a6-727bf4f786b6.jpg)

Same

**Comment by seadhy** [comment]
How can this be? Can you give me your Discord nickname?

**Comment by Harry1Botter** [comment]
TheTeacha#6002

**Comment by seadhy** [comment]
![image](https://user-images.githubusercontent.com/82868382/208266342-7088badb-4c6d-470d-b65a-6a0c9df1c888.png)
Solved 👍
